# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  dev:
    desc: Start the development server
    cmds:
      - bun run dev
    silent: true
  deploy:
    cmds:
      - bunx wrangler deploy
  tail:
    cmds:
      - bunx wrangler tail
  inspect:dev:
    desc: Start the inspector for debugging the local dev mcp server
    cmds:
      - bunx @modelcontextprotocol/inspector http://localhost:8787/mcp
  inspect:
    desc: Start the inspector
    cmds:
      - bunx @modelcontextprotocol/inspector
